"""followers

Revision ID: 20cfc5b808a7
Revises: 514cdf36b850
Create Date: 2021-03-13 17:05:08.908552

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "20cfc5b808a7"
down_revision = "514cdf36b850"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "followers",
        sa.Column("follower_id", sa.Integer(), nullable=True),
        sa.Column("followed_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["followed_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["follower_id"],
            ["user.id"],
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("followers")
    # ### end Alembic commands ###
